### ISSUE TITLE
Modelagem

### ISSUE THREAD

**Issue by lgnsparda** [Dinamica-dos-Fluidos-CFD/Alexandre_Carvalho-170004449#2]
- A frase: "O projeto realizado tem o intuito de especificar um determinado problema" não faz sentido. Um projeto de engenharia tem que propor uma solução, não especificar problema.
- Não se observou os requisitos de solução.
- A finalidade deve ser melhorada, está muito genérica.
- Esta etapa está incompleta.

**Comment by lgnsparda** [comment]
- A etapa de modelagem não foi corrigida

**Comment by lgnsparda** [comment]
- A parte de modelagem ainda não foi consolidada, não se deve fazer o pré-processamento antes disto!
- O seguinte parágrafo está deslocado: Após feita a parametrização das grandezas físicas, juntamente com as simulações computacionais, será possível apontar se existem incoerências na vazão e na perda de carga, e qual é a relevância destas características para a tubulação em si; e por meio de um estudo paramétrico da viscosidade do fluido, avaliar a normalidade do cenário suposto.
Sugere-se reescrevê-lo para adequa-lo ao objetivo.
- A primeira correção colocada não foi feita.

**Comment by AlexandrePCarvalho** [comment]
Creio que retifiquei todos os pontos ressaltados na modelagem. O sr. pode conferir novamente?
