### ISSUE TITLE
Processamento e pós processamento

### ISSUE THREAD

**Issue by lgnsparda** [Dinamica-dos-Fluidos-CFD/Alexandre_Carvalho-170004449#8]
- Sugere-se não colocar o tubo na vertical nas imagens, pode criar confusão.
- Melhorar as análises do estudo paramétrico

**Comment by lgnsparda** [comment]
- Nas imagens, colocar o tubo na posição horizontal
- As conclusões estão muito pobres. Esta parte deve ser refeita completamente.

**Comment by AlexandrePCarvalho** [comment]
Refiz as conclusões, de maneira mais objetiva, e reposicionei os tubos das simulações.

**Comment by lgnsparda** [comment]
Colocar o trabalho na forma de artigo científico

**Comment by lgnsparda** [comment]
Colocar o trabalho na forma de artigo científico

**Comment by AlexandrePCarvalho** [comment]
Estou trabalhando no artigo. Devo postá-lo ainda essa semana

**Comment by lgnsparda** [comment]
Colocar o trabalho na forma de relatório técnico
